{{- range .Values.gateways }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "istio-ingress" }}
spec:
  selector:
    istio: gateway
  servers:
  - port:
      number: 5432
      name: tcp-pgmain
      protocol: TCP
    hosts:
      - "*"
  - port:
      number: 5433
      name: tcp-pgrepl
      protocol: TCP
    hosts:
      - "*"
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
{{ toYaml .hosts | indent 4 }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .credentialName }}
    hosts:
{{ toYaml .hosts | indent 4 }}
{{- if .servers }}
{{ toYaml .servers | indent 2 }}
{{- end }}
{{- end}}