apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-istio
  namespace: istio-system
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:{{ .Values.jaeger.image.version | default "1.31"  }}
    options:
      log-level: debug
      query:
        base-path: /jaeger
        # prometheus:
        #   server-url: "http://kube-prometheus-stack-prometheus.monitoring:9090"
    # metricsStorage:
    #   type: prometheus
  storage:
    options:
      memory:
        max-traces: 100000
