apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: anonymous
  external_services:
    grafana:
      auth:
        password: {{ .Values.grafana.auth.password | default "prom-operator" | quote }}
        username: {{ .Values.grafana.auth.username | default "admin" | quote }}
        type: {{ .Values.grafana.auth.type | default "basic" | quote }}
        use_kiali_token: {{ .Values.grafana.auth.use_kiali_token | default "false" }}
      enabled: true
      url: {{ .Values.grafana.url | default "" }}
      in_cluster_url: http://kube-prometheus-stack-grafana.monitoring:80
      is_core: true
      dashboards:
      - name: "Istio Service Dashboard"
        variables:
          namespace: "var-namespace"
          service: "var-service"
      - name: "Istio Workload Dashboard"
        variables:
          namespace: "var-namespace"
          workload: "var-workload"
      - name: "Istio Mesh Dashboard"
      - name: "Istio Control Plane Dashboard"
      - name: "Istio Performance Dashboard"
      - name: "Istio Wasm Extension Dashboard"
    istio:
      component_status:
        components:
          - app_label: istiod
            is_core: true
            is_proxy: false
          - app_label: gateway
            is_core: true
            is_proxy: true
            namespace: istio-ingress
        enabled: true
    prometheus:
      url: http://kube-prometheus-stack-prometheus.monitoring:9090
    tracing:
      enabled: true
      url: {{ .Values.tracing.url | default "" }}
      in_cluster_url: http://jaeger-istio-query.istio-system:16686/jaeger
      is_core: false
      use_grpc: false
  istio_namespace: istio-system
