{{- $clusterissuer := .Values.clusterissuer}}
{{- range .Values.certificates }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "istio-ingress" }}
spec:
  commonName: {{ .commonname | quote }}
  dnsNames:
  - {{ .commonname | quote }}
  {{- if .additional_dnsnames }}
  {{- range .additional_dnsnames }}
  - {{ . | quote}}
  {{- end }}
  {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ $clusterissuer.name }}
  secretName: {{ .name  }}
{{- end}}