apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ci
  namespace: argocd
spec:
  description: cluster wide ci apps
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
